Add issue Github Action workflow
yychen/dj-registry pull request #7
Opened 2022-02-17 16:25 UTC by neo-maker-sudo

For Continuous integration of workflow about python package

2022-02-17 16:26 UTC, neo-maker-sudo commented
一直出錯，好醜0.0

2022-02-18 07:45 UTC, mattwang44 requested changes
@neo-maker-sudo Great job! Only a few minor issues need to be fixed!

2022-02-18 07:45 UTC, mattwang44 commented on .github/workflows/package.yaml
> +
Remove the empty line
```suggestion
```

2022-02-18 07:45 UTC, mattwang44 commented on .github/workflows/package.yaml
> +        python -m pip install flake8 poetry
Always leave a line break at end of the file.

```suggestion
        python -m pip install flake8 poetry

```

2022-02-18 07:45 UTC, mattwang44 commented on .github/workflows/package.yaml
> +name: Python package
This workflow tends to be executed on push or PR; therefore the workflow name `Python package` and the file name `package` does not fit the purpose. Changing it to `ci` or anything related would be more comprehensible.

```suggestion
name: CI
```

2022-02-18 07:49 UTC, mattwang44 commented
> 一直出錯，重複 commit，好醜0.0

@neo-maker-sudo 趁這個機會來學學怎麼整理 commit 吧！請你查一下怎麼使用 `git rebase` 這個指令，然後嘗試把**目前的 6 個 commits 合併成 1 個**～

2022-02-18 07:54 UTC, mattwang44 commented
Another tip is you can [link a PR to an issue with keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). For example, this PR resolves #4 .

2022-02-19 06:05 UTC, neo-maker-sudo commented on .github/workflows/package.yaml
> +
ok

2022-02-19 19:11 UTC, mattwang44 approved these changes
LGTM!

2022-02-19 19:11 UTC, merged